// 개발 노트 > 업데이트 기록 데이터.
// 규칙: 커밋/푸시할 때마다 해당 날짜 항목에 커밋 제목을 한 줄 추가한다. (CLAUDE.md 참고)

export type ChangeType = 'feat' | 'fix' | 'refactor' | 'ci' | 'docs' | 'chore' | 'perf' | 'test' | 'etc';
export type ChangelogDay = { date: string; items: { type: ChangeType; text: string }[] };

export const CHANGELOG: ChangelogDay[] = [
  { date: "2026-07-05", items: [
    { type: "feat", text: "노트 본문에 이미지 삽입 기능 추가 — 텍스트 앞뒤로 이미지 배치 가능" },
    { type: "feat", text: "클립보드 이미지(캡쳐 등) Ctrl+V로 노트 본문에 바로 붙여넣기 지원" },
  ] },
  { date: "2026-07-03", items: [
    { type: "refactor", text: "'연동 & 내보내기' 화면 정리 — 기능·안내 구분, 미구현 설명 삭제" },
    { type: "feat", text: "개발 노트 화면 신설 — 업데이트 기록 타임라인 + 개발 예정 백로그 탭" },
  ] },
  { date: "2026-07-02", items: [
    { type: "feat", text: "옵시디언 볼트 폴더 실시간 동기화 (File System Access API)" },
    { type: "fix", text: "볼트 동기화 안내 문구를 Chromium 계열 전체로 정정" },
    { type: "fix", text: "볼트 동기화 안내에서 Brave 관련 잘못된 정보 정정" },
    { type: "fix", text: "에디터 마크다운 왕복 변환 버그 3건 수정" },
    { type: "fix", text: "글씨 크기 조절 잔해(**) 생성 차단 + 요약 카드 마크다운 문법 숨김" },
    { type: "fix", text: "모바일 노트 카드·검색 결과에도 마크다운 서식 적용" },
    { type: "feat", text: "모바일에서 데스크탑과 동일한 노트 에디터 사용" },
    { type: "feat", text: "인앱 브라우저에서 구글 로그인 차단 안내 및 외부 브라우저 열기" },
    { type: "feat", text: "모바일 뒤로가기를 앱 내부 내비게이션으로 연결" },
    { type: "fix", text: "새 기기 로그인 시 초기 데이터가 서버를 덮어쓰는 동기화 사고 수정 + 백업/복구 체계" },
    { type: "fix", text: "서버 동기화 후 업로드 차단 플래그가 영원히 안 풀리는 버그 수정" },
    { type: "refactor", text: "죽은 코드·더미 데이터 대청소 + 모바일 첫 사용자 진입 흐름 보강" },
    { type: "feat", text: "모바일 내정보 탭에서 설정(테마·백업·복구) 접근 가능하게 연결" },
  ] },
  { date: "2026-07-01", items: [
    { type: "feat", text: "폴더별 노트 개수 배지 표시" },
    { type: "fix", text: "노트 개수 배지 폰트 크기를 폴더명보다 1px 작게 조정" },
    { type: "fix", text: "글씨 크기 변경 시 여백/구조 사라지는 버그 수정" },
    { type: "refactor", text: "글씨 크기 기능 전면 재구현" },
    { type: "fix", text: "글씨 크기 반복 조절 시 두 번째부터 적용 안 되던 문제 수정" },
    { type: "feat", text: "에디터 툴바에 현재 글씨 크기 뱃지 표시 + 기본 본문 크기 16px로 변경" },
    { type: "feat", text: "이모지 선택기 카테고리 탭 추가 + 이모지 752개로 확장" },
    { type: "fix", text: "이모지 고르기 모달 가로 30% 확장 + 우측 잘림 수정" },
    { type: "feat", text: "이모지 752개 → 999개로 확장" },
    { type: "fix", text: "기존 폴더에서 쓰던 이모지가 고르기 목록에 없던 문제 수정" },
    { type: "refactor", text: "이모지 카테고리 8개 → 14개로 세분화, 문자류 이모지 전부 제거" },
    { type: "fix", text: "글씨 크기 변경한 줄에서 엔터 줄바꿈이 안 되던 문제 수정" },
  ] },
  { date: "2026-06-30", items: [
    { type: "etc", text: "MVP 0.2 (몽글 디자인테마 수정중)" },
    { type: "feat", text: "MVP 0.3 - 노트 기능 추가중" },
    { type: "feat", text: "노트 에디터를 WYSIWYG 방식으로 전환" },
    { type: "feat", text: "노트 모달 UI 개선" },
    { type: "feat", text: "WYSIWYG 에디터 버그 수정 및 기능 확장" },
    { type: "fix", text: "WYSIWYG 에디터 버그 수정" },
    { type: "fix", text: "코드블록 Shift+Enter 및 구분선 너비 조절 기능 추가" },
    { type: "feat", text: "표 행/열 편집 툴바 및 글씨 크기 연속 조절 기능 추가" },
    { type: "fix", text: "코드창 리셋, 코드줄 테두리, 체크박스 토글 및 위치 버그 수정" },
    { type: "feat", text: "노트 모달/표 편집 UX 개선" },
    { type: "fix", text: "코드블록/표 삭제 및 드래그 선택 개선" },
  ] },
  { date: "2026-06-29", items: [
    { type: "fix", text: "로그인 redirectTo를 경로로 수정 (window.location.href → /)" },
    { type: "fix", text: "auth.config.ts Convex site URL 하드코딩 (process.env.CONVEX_SITE_URL undefined 문제)" },
    { type: "fix", text: "드래그 이동 시 maxDepth 깊이 제한 적용 (분류는 설정 깊이 이하만 허용)" },
    { type: "fix", text: "auth.config.ts를 portable 형태로 복원 (process.env.CONVEX_SITE_URL, dev/prod 양립)" },
    { type: "ci", text: "Vercel 빌드에서 production일 때 Convex prod 자동 배포 (push 한 번에 백엔드+프론트)" },
    { type: "fix", text: "서버가 빈 상태일 때 로컬 데이터가 Convex로 업로드되도록 수정 (첫 동기화 버그)" },
    { type: "fix", text: "프로덕션 프론트엔드가 prod Convex를 바라보도록 VITE_CONVEX_URL 주입 변수명 명시" },
    { type: "refactor", text: "기록함(leaf) 개념 제거 — 가장 깊은 카테고리가 기록을 직접 보유" },
    { type: "fix", text: "마이그레이션 시 혼합 노드(하위+기록)의 기록이 숨겨지지 않도록 전용 끝 노드로 분리" },
    { type: "fix", text: "convex 타입체크에서 process 미선언으로 prod 배포 실패하던 문제 해결" },
    { type: "fix", text: "깊이 기반 추가 모델로 통일 — 새 카테고리 하위분류 추가 가능 + maxDepth 설정 반영" },
    { type: "fix", text: "종단 판정을 깊이(depth==maxDepth) 기준으로 — maxDepth 증가 시 기존 기록 노드도 확장 가능" },
    { type: "refactor", text: "단계(maxDepth) 구분 폐지 — 모든 카테고리가 폴더+기록을 함께 보유" },
    { type: "feat", text: "폴더+기록 혼합 노드에 기록 개수 배지(+N) 표시" },
    { type: "feat", text: "하위 분류·기록이 있는 카테고리 삭제 시 확인 모달 표시" },
    { type: "fix", text: "기록 모달 세로 길이를 화면 높이의 70%로 확대 (입력 영역 확보)" },
    { type: "fix", text: "기록 내용 textarea가 모달 본문(태그 위까지) 전체 높이를 채우도록 수정" },
    { type: "feat", text: "기록 카드를 2줄 요약으로 표시 (더블클릭 시 전체 내용 편집 모달)" },
  ] },
  { date: "2026-06-26", items: [
    { type: "feat", text: "MVP 0.1 - 몽글 Study 초기 버전" },
    { type: "fix", text: "convex/_generated 빌드 파일 포함 (Vercel 빌드 오류 수정)" },
    { type: "fix", text: "Vercel 빌드 명령에서 tsc 분리 (vite build만 사용)" },
  ] },
];
